baseURL: "https://kkipngenokoech.github.io/mypage" 
title: Kipngeno Koech
pagination:
  pagerSize: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags
menu:
    main:
        - name: Home
          url: /
          weight: 1
        - name: More about me
          url: moreaboutme/
          weight: 2
        - name: Research
          url: papers/
          weight: 3
        - name: Teaching
          url: teaching/
          weight: 4
        - name: CV
          url: cv.pdf
          weight: 5
        - name: Portfolio
          url: https://github.com/kkipngenokoech
          weight: 6

params:
    description: "Graduate student in Engineering AI at Carnegie Mellon University Africa"
    author: Kipngeno Koech
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Kipngeno Koech
          subtitle: "Hi, I'm a **Masters student in Engineering Artificial Intelligence at Carnegie Mellon University Africa**. 
                    <br><br>
                    My research focuses on artificial intelligence and machine learning applications. I'm passionate about developing innovative AI solutions and exploring the intersection of technology and real-world problem solving.
                    <br><br>
                    Currently pursuing my graduate degree at CMU Africa, I'm actively involved in AI research and projects that leverage cutting-edge machine learning techniques.
                    <br><br>
                    **[Get in touch!](mailto:bkoech@andrew.cmu.edu)** I'd love to connect and discuss AI, machine learning, and technology innovation.
                    <br> 
                    *<small>Graduate student at Carnegie Mellon University Africa</small>
                    "
          imageUrl: "picture.png"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Kipngeno Koech
          buttons:
            - name: More about me
              url: moreaboutme/
            - name: Research
              url: papers/
            - name: Teaching
              url: teaching/
            - name: CV
              url: cv.pdf
            - name: Portfolio
              url: https://github.com/kkipngenokoech

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:bkoech@andrew.cmu.edu
        # - name: LinkedIn
          # url: https://www.linkedin.com/in/your-profile/
        - name : Google Scholar
          url: https://scholar.google.com/citations?user=YOURUSERID
        - name: GitHub
          url: https://github.com/kkipngenokoech
        - name: Twitter
          url: https://twitter.com/yourusername
        # - name: Zoom
          # url: https://ucl.zoom.us/my/zoom.tom.george 

    
    social:
        github: kkipngenokoech
        twitter: yourusername
        linkedin: your-profile


    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Kipngeno Koech"
      icon: picture.png
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
